---
- hosts: all
  become: yes
  tasks:
  - name: i want install webserver pn ansible nodes
    apt:
      name: apache2
      state: present
  - name: i want to start webserver on ubuntu ansible nodes
    service:
      name: apache2
      state: started
  