---
- hosts: all
  become: yes
  tasks:
  - name: i want install webserver pn ansible nodes
    apt:
      name: apache2
      state: present
    when: ansible_os_family=="Debian"
  - name: i want to start webserver on ubuntu ansible nodes
    service:
      name: apache2
      state: started
    when: ansible_os_family=="Debian"
  - name: i want install webserver on redhat nodes also
    yum:
      name: httpd
      state: present
    when: ansible_os_family=="RedHat"
  - name: i want to start webserver on RedHat nodes also
    service:
      name: httpd
      state: started
    when: ansible_os_family=="RetHat"
    